# Generated by Django 4.1.6 on 2023-02-10 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='grade_driver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
