# Generated by Django 4.1.6 on 2023-02-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_alter_grade_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
    ]
