# Generated by Django 4.1.6 on 2023-02-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(max_length=1500),
        ),
    ]
