# Generated by Django 4.1.4 on 2022-12-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number_alter_user_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin_view',
        ),
    ]
