# Generated by Django 4.1.4 on 2023-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(default=17829226, max_length=13),
            preserve_default=False,
        ),
    ]
